### ISSUE TITLE
ionic serve not working

### ISSUE THREAD

**Issue by ctwhome** [mappmechanic/ionic-firebase#1]
Hi! 
many thanks for the code and the guide, but executing ionic serve doesn't work. Works... but show a white page. Not clue why, apparently angular is loading and the rest of the libraries, but nothing, the application doesn't want to run...
regards

**Comment by vinnyglennon** [comment]
+1

**Comment by MrSkwiggs** [comment]
Hi, to resolve the problem, simply add ng-app="mychat" to the body directive :)

**Comment by aldhonie** [comment]
i was add ng-app="mychat" but still not working..
regards,

**Comment by batistafrancis** [comment]
Thanks @aldhonie ! :D

**Comment by chroda** [comment]
@aldhonie I have this problem, but I figured out you need stop/start server again

**Comment by mappmechanic** [comment]
I think this was resolved using @chroda pull request
